language: go
sudo: false
go:
  - 1.8
install:
  - go get github.com/Masterminds/glide
  - if ! go get github.com/golang/tools/cmd/cover; then go get golang.org/x/tools/cmd/cover; fi
script:
  - $GOPATH/bin/glide install
  - go test $($GOPATH/bin/glide novendor)
  
