
[[constraint]]
  name = "github.com/bshuster-repo/logrus-logstash-hook"
  version = "1.0.0-beta"

[[constraint]]
  branch = "master"
  name = "github.com/johntdyer/slackrus"

[[constraint]]
  name = "github.com/julienschmidt/httprouter"
  version = "^1.2"

[[constraint]]
  branch = "master"
  name = "github.com/justinas/alice"

[[constraint]]
  name = "github.com/newrelic/go-agent"
  version = "^2.1.0"

[[constraint]]
  name = "github.com/sirupsen/logrus"
  version = "1.0.4"

[[constraint]]
  name = "github.com/tomnomnom/linkheader"
  version = "0.1.0"

[[constraint]]
  name = "gopkg.in/throttled/throttled.v2"
  version = "2.0.3"

[[constraint]]
  branch = "v2"
  name = "gopkg.in/yaml.v2"

[[constraint]]
  name = "github.com/rubyist/circuitbreaker"
  version = "2.2.1"
